apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: user.openshift.io
      kind: Group
      name: cluster-admin-extra
    path: patch-cluster-admin-extra-group.yaml
  - target:
      group: user.openshift.io
      kind: Group
      name: rhods-admins
    path: patch-rhods-admins-group.yaml
