kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-extra
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: cluster-admin-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
