apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - dscinitialization.yaml
  - datasciencecluster.yaml
  - odh-dashboard-config.yaml
  - notebook-controller-culler-config-cm.yaml
  - hardwareprofile-cpu.yaml
  - hardwareprofile-default-disabled.yaml
  - hardwareprofile-gpu.yaml
  - model-catalog-sources.yaml
