apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-operators-appset.yaml
  - cluster-oper-instances-appset.yaml
  # demos appset is optional - use 'make demos' to deploy
